version: "3.9"


services:
  app:
    build:
      context: .
      args:
        - DEV=true
    image: goshopnow:v1.0
    ports:
      - "8000:8000"
    volumes:
     - ./app:/app
    command: >
     sh -c "python manage.py wait_for_db && 
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - es
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: "goshopnow"
    env_file:
      - .env
  celery:
    build: .
    command: celery --app=app worker --loglevel=info --beat
    volumes:
      - ./app:/app
    depends_on:
      - redis
    env_file:
      - .env
  redis:
    image: 'redis:alpine'
  es:
    image: elasticsearch:7.17.12
    environment:
      - discovery.type=single-node 
    ports:
      - 9200:9200
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  dev-db-data:
  es_data: