# Generated by Django 4.2.1 on 2023-06-06 14:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1.0, 'Minimum value muct be 1'), django.core.validators.MaxValueValidator(5.0, 'Maximum value must be 5')]),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(default=None, max_length=500, null=True)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id_review', to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
