# Generated by Django 4.2.1 on 2023-06-06 15:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_rating_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1.0, 'Minimum value muct be 1'), django.core.validators.MaxValueValidator(5.0, 'Maximum value must be 5')]),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='core.category'),
            preserve_default=False,
        ),
    ]
