# Generated by Django 4.2.3 on 2023-07-15 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_payment', to='core.product'),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('user', 'product')},
        ),
    ]
