# Generated by Django 4.2.3 on 2023-07-15 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_payment_product_alter_payment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('p_id', 'user')},
        ),
    ]
