# Generated by Django 4.2.3 on 2023-07-30 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_productimage_p_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='product',
        ),
        migrations.CreateModel(
            name='PaymentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_payment', to='core.product')),
            ],
        ),
    ]
