# Generated by Django 4.2.3 on 2023-07-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_payment_amount_remove_payment_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
