# Generated by Django 4.2.3 on 2023-07-30 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproduct',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
