# Generated by Django 4.2.5 on 2023-09-12 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1.0, 'Minimum value muct be 1'), django.core.validators.MaxValueValidator(5.0, 'Maximum value must be 5')]),
        ),
    ]
