# Generated by Django 4.2.5 on 2023-09-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tmp_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
