# Generated by Django 4.2.5 on 2023-09-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
