# Generated by Django 4.2.5 on 2023-09-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_payment_discount_amount_discountcoupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcoupon',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
